### ISSUE TITLE
Canvas task failed

### ISSUE THREAD

**Issue by morning-tan** [websoft9dev/role_ruby#14]
**Canvas on ubuntu 20.04 on AWS**
  
TASK [role_ruby : Rvm export, currently installed version effective immediately]                                                                                                                                                              ***
fatal: [54.208.47.200]: FAILED! => {"changed": true, "cmd": "rvm export -p", "de                                                                                                                                                             lta": "0:00:00.002816", "end": "2022-04-07 04:10:31.801816", "msg": "non-zero re                                                                                                                                                             turn code", "rc": 127, "start": "2022-04-07 04:10:31.799000", "stderr": "/bin/sh                                                                                                                                                             : 1: rvm: not found", "stderr_lines": ["/bin/sh: 1: rvm: not found"], "stdout":                                                                                                                                                              "", "stdout_lines": []}

  
![`QP$16(%B7FE60D79SZS0CC](https://user-images.githubusercontent.com/54173243/162133065-61af2d32-b21e-46e2-b08d-4cc0df90eab3.png)

**Comment by qiaofeng1227** [comment]
```
- name: Rvm export, currently installed version effective immediately
  shell: |
    source /etc/profile.d/rvm.sh --default executable=/bin/bash
    bash -lc "rvm export -p"
  
- name: Set default Ruby version
  shell: bash -lc "rvm use {{ruby_version}}"
  changed_when: False
```
