### ISSUE TITLE
add first app Rails

### ISSUE THREAD

**Issue by chendelin1982** [websoft9dev/role_ruby#5]
The same with Django, Express at role_node, role_python

**Comment by chendelin1982** [comment]
Rails can't access by Internet user?
```
rails s -b 0.0.0.0
```

**Comment by zengxc-1996** [comment]
9panel error:

![image](https://user-images.githubusercontent.com/63622990/122033018-bc56e580-ce02-11eb-8b4e-366908c1de1b.png)
