### ISSUE TITLE
ruby 2.4 not run

### ISSUE THREAD

**Issue by tqf6** [websoft9dev/role_ruby#7]
47.243.101.0
![image](https://user-images.githubusercontent.com/83911329/122182424-dbb24900-cebc-11eb-9526-93a0e83af886.png)

**Comment by tqf6** [comment]
阿里云 centos

**Comment by tqf6** [comment]
azure centos

**Comment by zengxc-1996** [comment]
```
bash -lc "gem install rails"

ERROR:  Error installing rails:
	There are no versions of activesupport (= 6.1.3.2) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	activesupport requires Ruby version >= 2.5.0. The current ruby version is 2.4.10.364.
```

**Comment by zengxc-1996** [comment]
rails not support ruby2.4

![image](https://user-images.githubusercontent.com/63622990/122189637-a9581a00-cec3-11eb-9a05-d12ed3849959.png)


[rails_url](https://guides.rubyonrails.org/getting_started.html)
